version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  rails:
    image: ruby:3.0.1
    command: bin/run.sh
    working_dir: /sample
    volumes:
      - .:/sample
    depends_on:
      - mysql